Repository Altinn/altinn-broker, pull requests merged in 2024-10, with the labels that each got.

#552 Fix Maskinporten token error
  src/Altinn.Broker.API/Helpers/AltinnTokenEventsHelper.cs
  src/Altinn.Broker.API/Helpers/JWTBearerEventsHelper.cs
  src/Altinn.Broker.API/Models/Maskinporten/MaskinportenSecurityTokenException.cs
  src/Altinn.Broker.API/Program.cs
Labels: kind/bug

#554 Fix postman collection for resource
  altinn-broker-postman-collection.json
Labels: kind/bug

#558 Added fields for grace period to collection file
  altinn-broker-postman-collection.json
Labels: kind/bug

#559 Fix: Require Download started before Confirmation
  src/Altinn.Broker.Application/ConfirmDownload/ConfirmDownloadHandler.cs
  src/Altinn.Broker.Application/Errors.cs
  tests/Altinn.Broker.Tests/FileTransferControllerTests.cs
  tests/Altinn.Broker.Tests/LegacyFileControllerTests.cs
Labels: kind/bug

#560 Add shim for manifest file
  altinn-broker-openapi-v1.json
  altinn-broker-postman-collection.json
  src/Altinn.Broker.API/Controllers/ResourceController.cs
  src/Altinn.Broker.API/Models/ResourceExt.cs
  src/Altinn.Broker.Application/ConfigureResource/ConfigureResourceHandler.cs
  src/Altinn.Broker.Application/ConfigureResource/ConfigureResourceRequest.cs
  src/Altinn.Broker.Application/DownloadFile/DownloadFileHandler.cs
  src/Altinn.Broker.Core/Domain/ResourceEntity.cs
  src/Altinn.Broker.Core/Helpers/BrokerServiceManifest.cs
  src/Altinn.Broker.Core/Helpers/IManifestDownloadStream.cs
  src/Altinn.Broker.Core/Helpers/ManifestDownloadStream.cs
  src/Altinn.Broker.Core/Repositories/IResourceRepository.cs
  src/Altinn.Broker.Persistence/Altinn.Broker.Persistence.csproj
  src/Altinn.Broker.Persistence/Migrations/V0008__manifest_shim.sql
  src/Altinn.Broker.Persistence/Repositories/ResourceRepository.cs
  tests/Altinn.Broker.Tests/Altinn.Broker.Tests.csproj
  tests/Altinn.Broker.Tests/Data/ManifestFileTests/Manifest.xml
  tests/Altinn.Broker.Tests/Data/ManifestFileTests/Payload.zip
  tests/Altinn.Broker.Tests/Data/ManifestFileTests/PayloadWithExistingManifest.zip
  tests/Altinn.Broker.Tests/Data/ManifestFileTests/payload.txt
  tests/Altinn.Broker.Tests/Data/R__Prepare_Test_Data.sql
  tests/Altinn.Broker.Tests/Factories/FileTransferEntityFactory.cs
  tests/Altinn.Broker.Tests/Factories/FileTransferInitializeExtTestFactory.cs
  tests/Altinn.Broker.Tests/Helpers/ManifestDownloadStreamHelpers.cs
  tests/Altinn.Broker.Tests/Helpers/TestConstants.cs
  tests/Altinn.Broker.Tests/LegacyFileControllerTests.cs
  tests/Altinn.Broker.Tests/ManifestDownloadStreamTests.cs
Labels: kind/feature

#565 Add Workflow to verify future PRs contain a label that is used for release notes
  .github/workflows/check-label-for-pr.yml
Labels: kind/chore, ignore-for-release
