Repository Altinn/altinn-broker, pull requests merged in 2024-11, with the labels that each got.

#567 Add custom configuration for renovate bot
  renovate.json
Labels: kind/chore

#562 Feature/add exception handling
  .azure/infrastructure/main.bicep
  .azure/infrastructure/params.bicepparam
  .azure/modules/containerApp/main.bicep
  .azure/modules/containerAppEnvironment/main.bicep
  .github/actions/update-infrastructure/action.yml
  .github/workflows/deploy-to-environment.yml
  src/Altinn.Broker.API/Helpers/SecurityHeadersMiddleware.cs
  src/Altinn.Broker.API/Helpers/SlackExceptionNotification.cs
  src/Altinn.Broker.API/Program.cs
  src/Altinn.Broker.API/appsettings.Development.json
  src/Altinn.Broker.Application/Altinn.Broker.Application.csproj
  src/Altinn.Broker.Core/Options/GeneralSettings.cs
  src/Altinn.Broker.Integrations/Altinn.Broker.Integrations.csproj
  src/Altinn.Broker.Integrations/DependencyInjection.cs
  src/Altinn.Broker.Integrations/Slack/SlackDevClient.cs
Labels: kind/feature

#582 Support large files
  .azure/modules/containerApp/main.bicep
  Altinn.Broker.sln
  docs/TestingLargeFile.md
  src/Altinn.Broker.API/Controllers/FileTransferController.cs
  src/Altinn.Broker.API/Controllers/HealthController.cs
  src/Altinn.Broker.API/Controllers/ServiceOwnerController.cs
  src/Altinn.Broker.API/Mappers/FileStatusOverviewExtMapper.cs
  src/Altinn.Broker.API/Mappers/FileTransferStatusDetailsExtMapper.cs
  src/Altinn.Broker.API/Mappers/InitializeFileTransferMapper.cs
  src/Altinn.Broker.API/Models/FileTransferInitializeExt.cs
  src/Altinn.Broker.API/Models/FileTransferOverviewExt.cs
  src/Altinn.Broker.API/Models/ServiceOwner/ServiceOwnerOverviewExt.cs
  src/Altinn.Broker.API/Program.cs
  src/Altinn.Broker.API/Properties/launchSettings.json
  src/Altinn.Broker.API/appsettings.Development.json
  src/Altinn.Broker.Application/ApplicationConstants.cs
  src/Altinn.Broker.Application/ApplicationSettings.cs
  src/Altinn.Broker.Application/ConfigureResource/ConfigureResourceHandler.cs
  src/Altinn.Broker.Application/ConfirmDownload/ConfirmDownloadHandler.cs
  src/Altinn.Broker.Application/DownloadFile/DownloadFileHandler.cs
  src/Altinn.Broker.Application/Errors.cs
  src/Altinn.Broker.Application/InitializeFileTransfer/InitializeFileTransferHandler.cs
  src/Altinn.Broker.Application/InitializeFileTransfer/InitializeFileTransferRequest.cs
  src/Altinn.Broker.Application/UploadFile/UploadFileHandler.cs
  src/Altinn.Broker.Core/Domain/Enums/StorageProviderType.cs
  src/Altinn.Broker.Core/Domain/FileTransferEntity.cs
  src/Altinn.Broker.Core/Domain/ResourceEntity.cs
  src/Altinn.Broker.Core/Domain/ServiceOwnerEntity.cs
  src/Altinn.Broker.Core/Domain/StorageProviderEntity.cs
  src/Altinn.Broker.Core/Options/GeneralSettings.cs
  src/Altinn.Broker.Core/Repositories/IFileTransferRepository.cs
  src/Altinn.Broker.Core/Services/IBrokerStorageService.cs
  src/Altinn.Broker.Core/Services/IResourceManager.cs
  src/Altinn.Broker.Integrations/Altinn/Events/AltinnEventBus.cs
  src/Altinn.Broker.Integrations/Azure/AzureResourceManagerService.cs
  src/Altinn.Broker.Integrations/Azure/AzureStorageOptions.cs
  src/Altinn.Broker.Integrations/Azure/AzureStorageService.cs
  src/Altinn.Broker.Integrations/Azure/BlobService.cs
  src/Altinn.Broker.Integrations/DependencyInjection.cs
  src/Altinn.Broker.Persistence/Altinn.Broker.Persistence.csproj
  src/Altinn.Broker.Persistence/DependencyInjection.cs
  src/Altinn.Broker.Persistence/Migrations/V0010__toggleable_virusscan.sql
  src/Altinn.Broker.Persistence/Repositories/FileTransferRepository.cs
  src/Altinn.Broker.Persistence/Repositories/ServiceOwnerRepository.cs
  tests/Altinn.Broker.Tests.LargeFile/Altinn.Broker.Tests.LargeFile.csproj
  tests/Altinn.Broker.Tests.LargeFile/Dockerfile
  tests/Altinn.Broker.Tests.LargeFile/Program.cs
  tests/Altinn.Broker.Tests.LargeFile/PseudoRandomDataStream.cs
  tests/Altinn.Broker.Tests/Data/R__Prepare_Test_Data.sql
Labels: kind/feature

#589 Make Authorization service more testable by passing ClaimsPrincipal as argument
  src/Altinn.Broker.API/Controllers/FileTransferController.cs
  src/Altinn.Broker.API/Controllers/LegacyFileController.cs
  src/Altinn.Broker.API/Controllers/MalwareScanResultsController.cs
  src/Altinn.Broker.API/Controllers/ResourceController.cs
  src/Altinn.Broker.Application/ConfigureResource/ConfigureResourceHandler.cs
  src/Altinn.Broker.Application/ConfirmDownload/ConfirmDownloadHandler.cs
  src/Altinn.Broker.Application/DownloadFile/DownloadFileHandler.cs
  src/Altinn.Broker.Application/ExpireFileTransfer/ExpireFileTransferHandler.cs
  src/Altinn.Broker.Application/GetFileTransferDetails/GetFileTransferDetailsHandler.cs
  src/Altinn.Broker.Application/GetFileTransferOverview/GetFileTransferOverviewHandler.cs
  src/Altinn.Broker.Application/GetFileTransfers/GetFileTransfersHandler.cs
  src/Altinn.Broker.Application/GetFileTransfers/LegacyGetFilesHandler.cs
  src/Altinn.Broker.Application/IHandler.cs
  src/Altinn.Broker.Application/InitializeFileTransfer/InitializeFileTransferHandler.cs
  src/Altinn.Broker.Application/MalwareScanResults/MalwareScanResultHandler.cs
  src/Altinn.Broker.Application/UploadFile/UploadFileHandler.cs
  src/Altinn.Broker.Core/Repositories/IAuthorizationService.cs
  src/Altinn.Broker.Integrations/Altinn/Authorization/AltinnAuthorizationService.cs
  tests/Altinn.Broker.Tests/Helpers/CustomWebApplicationFactory.cs
Labels: kind/chore

#590 fix that deploy needs test
  .github/workflows/ci-cd.yaml
Labels: kind/bug
