Repository Altinn/altinn-broker, pull requests merged in 2025-06, with the labels that each got.

#736 Fix flaky tests caused by failure to get distributed lock
  tests/Altinn.Broker.Tests/Helpers/CustomWebApplicationFactory.cs
Labels: kind/chore

#737 Slacknotification to correct channel for stuck filetransfers
  src/Altinn.Broker.Application/StuckFileTransfer/SlackStuckFileTransferNotifier.cs
  tests/Altinn.Broker.Tests/StuckFileTransferHandlerTests.cs
Labels: kind/chore

#741 polly retries for network calls
  src/Altinn.Broker.Application/Altinn.Broker.Application.csproj
  src/Altinn.Broker.Core/Altinn.Broker.Core.csproj
  src/Altinn.Broker.Core/Helpers/HttpClientBuilderExtensions.cs
  src/Altinn.Broker.Integrations/DependencyInjection.cs
  tests/Altinn.Broker.Tests/HttpRetryPolicyTests.cs
Labels: kind/feature

#749 Accept resourceid in urn format
  src/Altinn.Broker.API/Mappers/InitializeFileTransferMapper.cs
  src/Altinn.Broker.API/Models/FileTransferInitializeExt.cs
  src/Altinn.Broker.API/Models/LegacyFileInitializeExt.cs
  src/Altinn.Broker.API/ValidationAttributes/MD5ChecksumAttribute.cs
  src/Altinn.Broker.API/ValidationAttributes/PropertyListAttribute.cs
  src/Altinn.Broker.API/ValidationAttributes/ResourceIdentifierAttribute.cs
  src/Altinn.Broker.Common/Constants/UrnConstants.cs
  src/Altinn.Broker.Common/StringExtensions.cs
  src/Altinn.Broker.Integrations/Altinn/Authorization/XacmlMappers.cs
  tests/Altinn.Broker.Tests/AcceptHeaderValidationTests.cs
  tests/Altinn.Broker.Tests/FileTransferControllerTests.cs
Labels: kind/feature-request

#748 Update Postman collection for system user
  altinn-broker-postman-collection.json
Labels: kind/chore
