Repository Altinn/altinn-broker, pull requests merged in 2025-01, with the labels that each got.

#615 Upgrade Broker to dotnet version 9
  .github/workflows/codeql.yml
  .github/workflows/test-application.yml
  .github/workflows/validate-formatting.yml
  Dockerfile
  src/Altinn.Broker.API/Altinn.Broker.API.csproj
  src/Altinn.Broker.Application/Altinn.Broker.Application.csproj
  src/Altinn.Broker.Core/Altinn.Broker.Core.csproj
  src/Altinn.Broker.Integrations/Altinn.Broker.Integrations.csproj
  src/Altinn.Broker.Persistence/Altinn.Broker.Persistence.csproj
  tests/Altinn.Broker.Tests.LargeFile/Altinn.Broker.Tests.LargeFile.csproj
  tests/Altinn.Broker.Tests/Altinn.Broker.Tests.csproj
Labels: kind/chore

#617 Disablet parallelisering for tester
  tests/Altinn.Broker.Tests/Altinn.Broker.Tests.csproj
Labels: kind/bug

#632 Change serviceowner scope
  altinn-broker-postman-collection.json
  src/Altinn.Broker.API/Configuration/AuthorizationConstants.cs
  tests/Altinn.Broker.Tests.LargeFile/Program.cs
  tests/Altinn.Broker.Tests/Helpers/TestConstants.cs
Labels: kind/user-story
