Repository Altinn/altinn-broker, pull requests merged in 2025-02, with the labels that each got.

#636 created middleware to validate the Accept header of incoming requests
  altinn-broker-postman-collection.json
  src/Altinn.Broker.API/Controllers/FileTransferController.cs
  src/Altinn.Broker.API/Controllers/ServiceOwnerController.cs
  src/Altinn.Broker.API/Helpers/AcceptHeaderValidationMiddleware.cs
  src/Altinn.Broker.API/Program.cs
  tests/Altinn.Broker.Tests/AcceptHeaderValidationTests.cs
  tests/Altinn.Broker.Tests/Helpers/CustomWebApplicationFactory.cs
Labels: kind/feature

#641 Fix initialize filetranfer 500 response
  src/Altinn.Broker.Persistence/Repositories/ResourceRepository.cs
Labels: kind/bug

#654 update pr label check
  .github/workflows/check-label-for-pr.yml
Labels: kind/chore

#655 update swagger with much more details
  src/Altinn.Broker.API/Altinn.Broker.API.csproj
  src/Altinn.Broker.API/Controllers/FileTransferController.cs
  src/Altinn.Broker.API/Controllers/HealthController.cs
  src/Altinn.Broker.API/Controllers/LegacyFileController.cs
  src/Altinn.Broker.API/Controllers/MalwareScanResultsController.cs
  src/Altinn.Broker.API/Controllers/ResourceController.cs
  src/Altinn.Broker.API/Controllers/ServiceOwnerController.cs
  src/Altinn.Broker.API/Models/FileTransferInitializeAndUploadExt.cs
  src/Altinn.Broker.API/Models/FileTransferInitializeExt.cs
  src/Altinn.Broker.API/Models/FileTransferInitializeResponseExt.cs
  src/Altinn.Broker.API/Models/FileTransferOverviewExt.cs
  src/Altinn.Broker.API/Models/FileTransferStatusDetailsExt.cs
  src/Altinn.Broker.API/Models/FileTransferStatusEventExt.cs
  src/Altinn.Broker.API/Models/FileTransferUploadResponseExt.cs
  src/Altinn.Broker.API/Models/Recipient/RecipientFileStatusDetailsExt.cs
  src/Altinn.Broker.API/Models/Recipient/RecipientFileStatusEventExt.cs
  src/Altinn.Broker.API/Models/ResourceExt.cs
  src/Altinn.Broker.API/Models/ServiceOwner/ServiceOwnerInitializeExt.cs
  src/Altinn.Broker.API/Models/ServiceOwner/ServiceOwnerOverviewExt.cs
  src/Altinn.Broker.API/Program.cs
  src/Altinn.Broker.Application/DownloadFile/DownloadFileHandler.cs
  src/Altinn.Broker.Application/InitializeFileTransfer/InitializeFileTransferHandler.cs
Labels: kind/documentation
