Repository Altinn/altinn-broker, pull requests merged in 2025-03, with the labels that each got.

#658 Fix Renovate setup for Bicep
  renovate.json
  src/Altinn.Broker.API/Altinn.Broker.API.csproj
  src/Altinn.Broker.Application/Altinn.Broker.Application.csproj
  src/Altinn.Broker.Core/Altinn.Broker.Core.csproj
  src/Altinn.Broker.Integrations/Altinn.Broker.Integrations.csproj
  src/Altinn.Broker.Persistence/Altinn.Broker.Persistence.csproj
  tests/Altinn.Broker.Tests.LargeFile/Altinn.Broker.Tests.LargeFile.csproj
  tests/Altinn.Broker.Tests/Altinn.Broker.Tests.csproj
Labels: kind/chore

#656 Feat/block external access
  .azure/applications/api/main.bicep
  .azure/applications/api/params.bicepparam
  .azure/modules/containerApp/fetchEventGridIps.bicep
  .azure/modules/containerApp/main.bicep
  src/Altinn.Broker.API/Program.cs
  src/Altinn.Broker.Application/IpSecurityRestrictionsUpdater/IpSecurityRestrictionsUpdater.cs
  src/Altinn.Broker.Core/Altinn.Broker.Core.csproj
  src/Altinn.Broker.Core/Services/IResourceManager.cs
  src/Altinn.Broker.Integrations/Altinn.Broker.Integrations.csproj
  src/Altinn.Broker.Integrations/Azure/AzureResourceManagerOptions.cs
  src/Altinn.Broker.Integrations/Azure/AzureResourceManagerService.cs
Labels: kind/feature

#659 Use environment variable for Maskinporten environment
  .azure/applications/api/params.bicepparam
  .github/actions/update-infrastructure/action.yml
  .github/workflows/deploy-to-environment.yml
Labels: kind/bug

#664 Use MASKINPORTEN_ENVIRONMENT in correct deployment
  .github/actions/release-version/action.yml
  .github/actions/update-infrastructure/action.yml
  .github/workflows/deploy-to-environment.yml
Labels: kind/bug

#660 Get resource endpoint
  .github/actions/update-infrastructure/action.yml
  .github/workflows/deploy-to-environment.yml
  altinn-broker-postman-collection.json
  src/Altinn.Broker.API/Controllers/ResourceController.cs
  src/Altinn.Broker.API/Helpers/ValidateUseManifestFileShim.cs
  src/Altinn.Broker.Application/DependencyInjection.cs
  src/Altinn.Broker.Application/GetResource/GetResourceHandler.cs
Labels: kind/feature

#671 add missing indices for created sender_actor_id_fk
  src/Altinn.Broker.Persistence/Migrations/V0012__optimize_legacy_search2.sql
Labels: kind/feature

#672 Added sorting based on Created to Legacy.GetFiles
  src/Altinn.Broker.Persistence/Repositories/FileTransferRepository.cs
  tests/Altinn.Broker.Tests/LegacyFileControllerTests.cs
Labels: kind/bug, product/formidling

#670 Retrieve APIM IP from Github environment secrets
  .azure/applications/api/params.bicepparam
  .github/actions/release-version/action.yml
  .github/workflows/deploy-to-environment.yml
Labels: kind/feature

#680 Add detailed explaination of errors
  src/Altinn.Broker.API/Controllers/FileTransferController.cs
  src/Altinn.Broker.API/Controllers/ResourceController.cs
  src/Altinn.Broker.API/Controllers/ServiceOwnerController.cs
Labels: kind/documentation

#667 Added slack integration for hangfire and prod
  src/Altinn.Broker.API/Controllers/FileTransferController.cs
  src/Altinn.Broker.Core/Options/SlackSettings.cs
  src/Altinn.Broker.Integrations/DependencyInjection.cs
  src/Altinn.Broker.Integrations/Hangfire/DependencyInjection.cs
  src/Altinn.Broker.Integrations/Hangfire/SlackExceptionHandler.cs
  src/Altinn.Broker.Integrations/Slack/SlackDevClient.cs
  src/Altinn.Broker.Integrations/Slack/SlackExceptionNotificationHandler.cs
Labels: kind/chore

#688 Fix malwarescan webhook failures
  src/Altinn.Broker.API/Controllers/MalwareScanResultsController.cs
  src/Altinn.Broker.Application/MalwareScanResults/MalwareScanResultHandler.cs
  src/Altinn.Broker.Core/Services/IBrokerStorageService.cs
  src/Altinn.Broker.Integrations/Azure/AzureStorageService.cs
Labels: kind/bug

#689 Should throw exception and be retried if these queries fail
  src/Altinn.Broker.Application/MalwareScanResults/MalwareScanResultHandler.cs
Labels: kind/bug

#687 Feat/notification for files stuck in uploadprocessing
  src/Altinn.Broker.API/Program.cs
  src/Altinn.Broker.Application/DependencyInjection.cs
  src/Altinn.Broker.Application/StuckFileTransfer/SlackStuckFileTransferNotifier.cs
  src/Altinn.Broker.Application/StuckFileTransfer/StuckFileTransferHandler.cs
  src/Altinn.Broker.Core/Repositories/IFileTransferStatusRepository.cs
  src/Altinn.Broker.Persistence/Repositories/FileTransferStatusRepository.cs
  tests/Altinn.Broker.Tests/StuckFileTransferHandlerTests.cs
Labels: kind/feature
