Repository Altinn/altinn-broker, pull requests merged in 2025-04, with the labels that each got.

#691 Remove old idempotency code
  src/Altinn.Broker.API/Controllers/FileTransferController.cs
  src/Altinn.Broker.API/Controllers/MalwareScanResultsController.cs
  src/Altinn.Broker.API/Helpers/IdempotencyEventHelper.cs
  src/Altinn.Broker.API/Program.cs
  src/Altinn.Broker.Application/MalwareScanResults/MalwareScanResultHandler.cs
  src/Altinn.Broker.Core/Repositories/IIdempotencyEventRepository.cs
  src/Altinn.Broker.Integrations/DependencyInjection.cs
  src/Altinn.Broker.Integrations/Hangfire/IdempotencyService.cs
  src/Altinn.Broker.Persistence/DependencyInjection.cs
  src/Altinn.Broker.Persistence/Repositories/IdempotencyEventRepository.cs
  tests/Altinn.Broker.Tests/MalwareScanResultControllerTests.cs
Labels: kind/bug

#692 Disable adaptive sampling
  src/Altinn.Broker.API/Program.cs
Labels: kind/chore

#698 Strukturert data i ContainerAppConsoleLogs_CL
  src/Altinn.Broker.API/Helpers/PropertyPropagationEnricher.cs
  src/Altinn.Broker.API/Program.cs
Labels: kind/feature-request

#714 Downgrade azure cli to 2.70 because of bug in version 2.71
  .github/actions/update-infrastructure/action.yml
Labels: kind/chore

#716 Remove duplicate SlackExceptionNotification class
  src/Altinn.Broker.API/Helpers/SlackExceptionNotification.cs
  src/Altinn.Broker.API/Program.cs
Labels: kind/chore

#717 Added keepalive to database connection
  src/Altinn.Broker.Application/IpSecurityRestrictionsUpdater/IpSecurityRestrictionsUpdater.cs
  src/Altinn.Broker.Persistence/DependencyInjection.cs
Labels: kind/chore
